version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: build
      prefix-development: build
      include: scope
    labels:
      - "build"
      - "bun"
      - "dependabot"
      - "dependencies"
